import httpx
from typing import Optional, Dict, Any, List
from uuid import uuid4
from pydantic import BaseModel, Field

from arp.models import Principal

class WalletBalance(BaseModel):
    amount: str = Field(..., description="The balance amount")
    currency: str = Field(..., description="The asset or currency ticker (e.g., USDC, EURC)")

class Wallet(BaseModel):
    id: str = Field(..., description="Unique Wallet ID generated by Circle")
    state: str = Field(..., description="Current state of the wallet (e.g., LIVE)")
    walletSetId: str = Field(..., description="The ID of the wallet set")
    custodyType: str = Field(..., description="Custody type (e.g., DEVELOPER)")
    address: str = Field(..., description="On-chain wallet address")
    blockchain: str = Field(..., description="Blockchain network (e.g., ETH-SEPOLIA)")
    accountType: Optional[str] = Field(None, description="Account Type (SCA, EOA)")
    updateDate: str = Field(..., description="Last update timestamp")
    createDate: str = Field(..., description="Creation timestamp")
    balances: Optional[List[WalletBalance]] = Field(None, description="Current token balances")

class CircleClient:
    """
    A professional, async Python interface for Circle's Web3 Services API.
    Handles the provisioning and management of Developer-Controlled Programmable 
    Wallets for the Agent Remittance Protocol.
    """

    def __init__(self, api_key: str, base_url: str = "https://api.circle.com/v1/w3s"):
        """
        Initializes the Circle Web3 Services client.
        
        Args:
            api_key (str): Circle API Key.
            base_url (str): The base URL for Circle Web3 Services.
        """
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        
    def _get_client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(
            base_url=self.base_url,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            },
            timeout=15.0
        )

    async def create_programmable_wallet(
        self, 
        user: Principal, 
        wallet_set_id: str, 
        blockchain: str = "ETH-SEPOLIA",
        account_type: str = "SCA"
    ) -> Wallet:
        """
        Provisions a Developer-Controlled Programmable Wallet tailored to a specific ARP principal.
        
        Args:
            user (Principal): The ARP principal (Retail or Corporate) object.
            wallet_set_id (str): The ID of the wallet set to create the wallet within.
            blockchain (str): The target blockchain network.
            account_type (str): Smart Contract Account (SCA) or Externally Owned Account (EOA).
            
        Returns:
            Wallet: Pydantic model representing the provisioned wallet data.
        """
        idempotency_key = str(uuid4())
        payload = {
            "idempotencyKey": idempotency_key,
            "blockchains": [blockchain],
            "accountType": account_type,
            "walletSetId": wallet_set_id,
            "metadata": [
                {
                    "name": f"ARP Wallet - {user.name} ({user.principal_type.value})",
                    "refId": user.id
                }
            ]
        }

        async with self._get_client() as client:
            response = await client.post("/developer/wallets", json=payload)
            response.raise_for_status()
            
            data = response.json().get("data", {})
            wallets = data.get("wallets", [])
            
            if not wallets:
                raise ValueError("Circle API returned success but no wallet data was provisioned.")
                
            return Wallet(**wallets[0])
            
    async def get_wallet_balances(self, wallet_id: str) -> List[WalletBalance]:
        """
        Retrieves the token balances for a specific programmable wallet.
        
        Args:
            wallet_id (str): The ID of the wallet to query.
            
        Returns:
            List[WalletBalance]: A list of wallet balances.
        """
        async with self._get_client() as client:
            response = await client.get(f"/wallets/{wallet_id}/balances")
            response.raise_for_status()
            
            data = response.json().get("data", {})
            token_balances = data.get("tokenBalances", [])
            
            return [WalletBalance(**balance) for balance in token_balances]
